//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace menu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tovaroved
    {
        public int Id { get; set; }
        public string zak { get; set; }
        public string ost { get; set; }
        public string otst { get; set; }
    }
}
