//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace menu
{
    using System;
    using System.Collections.Generic;
    
    public partial class zakupchik
    {
        public int Id { get; set; }
        public int Idmark { get; set; }
        public int Idtov { get; set; }
        public string pok { get; set; }
        public long price { get; set; }
        public Nullable<int> kol { get; set; }
    }
}
